-- 보유 게임 정보 갱신 (출처: 보드게임_컬렉션_정리.md, 2026-10-10)
-- 여러 번 실행해도 안전: 기존 행은 id로 덮어쓰고, 새 게임은 같은 이름이 없을 때만 추가
-- 이미 올려둔 이미지는 그대로 두고, 이미지가 없는 게임에만 BGG 이미지 주소를 채움

insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '머더미스터리', '구두룡 저택의 살인', '九頭竜館の殺人 (The Murder at Cthulhu Manor)', '머더미스터리 (그룹SNE 미스터리 파티 인 더 박스)', null, '7~9인', 120, 'https://www.groupsne.co.jp/products/bg/mpb/mpb01.html', null, 'https://www.groupsne.co.jp/products/bg/mpb/img/mpb01_top.png' where not exists (select 1 from games where name = '구두룡 저택의 살인');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '머더미스터리', '늑대인간 마을의 축제', '人狼村の祝祭 (The Tale of Twilight Wolves)', '머더미스터리', null, '7~8인', 120, 'https://www.groupsne.co.jp/products/bg/mpb/mpb03.html', null, 'https://www.groupsne.co.jp/products/bg/mpb/img/mpb03_top.png' where not exists (select 1 from games where name = '늑대인간 마을의 축제');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '머더미스터리', '다크 율에 속죄를', 'ダークユールに贖いを', '머더미스터리 (고난도)', null, '7~9인', 180, 'https://www.groupsne.co.jp/products/bg/mpb/mpb04.html', null, 'https://www.groupsne.co.jp/products/bg/mpb/img/mpb04_top.png' where not exists (select 1 from games where name = '다크 율에 속죄를');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '머더미스터리', '게놈의 탑', 'ゲノムの塔', '머더미스터리', null, '7인', 180, 'https://www.groupsne.co.jp/products/bg/mpb/mpb17.html', null, 'https://www.groupsne.co.jp/products/bg/mpb/img/mpb17_top.png' where not exists (select 1 from games where name = '게놈의 탑');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '머더미스터리', '죄와 벌의 도서관', '罪と罰の図書館', '머더미스터리', null, '5~6인', 150, 'https://www.groupsne.co.jp/products/bg/mpb/mpb14.html', null, 'https://www.groupsne.co.jp/products/bg/mpb/img/mpb14_top.png' where not exists (select 1 from games where name = '죄와 벌의 도서관');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '머더미스터리', '용사가 죽었다', 'Mystery Party in the Box: The Brave is Dead', '머더미스터리, 롤플레잉', null, '6~8인', 180, 'https://boardlife.co.kr/game/17173', null, 'https://img.boardlife.co.kr/wys2/swf_upload/2023/07/11/1689012816263960_lg.jpg' where not exists (select 1 from games where name = '용사가 죽었다');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '머더미스터리', '오늘 내가 죽었다', 'I Died Today (일본판 今日、私は死んだ)', '머더미스터리', null, '5인', 120, 'https://boardlife.co.kr/game/21953', null, null where not exists (select 1 from games where name = '오늘 내가 죽었다');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '머더미스터리', '괴조는 깊은 탄식의 끝에', 'At the End of a Giant Bird''s Deep Sigh (작가 さくべえ, 2025)', '머더미스터리', null, null, null, 'https://boardlife.co.kr/game/21806', null, null where not exists (select 1 from games where name = '괴조는 깊은 탄식의 끝에');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '보드게임', '아발론 (구슬게임)', 'Abalone', '추상전략', null, '2인', 30, 'https://boardgamegeek.com/boardgame/526', 526, 'https://cf.geekdo-images.com/UzH1jAlqYUH9VEq2Wtvzjw__itemrep/img/6-Y9M20VQ73LL_d8zG0PGz9_Rh0=/fit-in/246x300/filters:strip_icc()/pic5253079.jpg' where not exists (select 1 from games where name = '아발론 (구슬게임)');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '보드게임', '아베 시저', 'Ave Caesar', '레이싱, 가족', null, '2~6인', 30, 'https://boardgamegeek.com/boardgame/494', 494, 'https://cf.geekdo-images.com/jfsOYuwuwuTwx-2ggixX0g__itemrep/img/g_PfPhUBwrr59XbUMmyqt9r-rPA=/fit-in/246x300/filters:strip_icc()/pic7074363.jpg' where not exists (select 1 from games where name = '아베 시저');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '보드게임', '광합성', 'Photosynthesis', '추상전략, 가족', null, '2~4인', 60, 'https://boardgamegeek.com/boardgame/218603', 218603, 'https://cf.geekdo-images.com/HhkYuVxMy-XrRCBWmZ78Eg__itemrep/img/WkJh5sVmz8F92ekuvSnHHebZA7I=/fit-in/246x300/filters:strip_icc()/pic3364832.jpg' where not exists (select 1 from games where name = '광합성');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '보드게임', '딥씨 크루: 심해에서의 임무', 'The Crew: Mission Deep Sea', '협력 트릭테이킹, 카드', null, '2~5인', 20, 'https://boardgamegeek.com/boardgame/324856', 324856, 'https://cf.geekdo-images.com/VuBqZ1sMaDAVVHF_OEJP4g__itemrep/img/tgB3g7PECxG14yQ0FkMiMaXaOFE=/fit-in/246x300/filters:strip_icc()/pic5988903.jpg' where not exists (select 1 from games where name = '딥씨 크루: 심해에서의 임무');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '보드게임', '스페이스 크루: 9번째 행성을 찾아서', 'The Crew: The Quest for Planet Nine', '협력 트릭테이킹, 카드', null, '2~5인', 20, 'https://boardgamegeek.com/boardgame/284083', 284083, 'https://cf.geekdo-images.com/98LnQShydr11OBKS46xY-Q__itemrep/img/etVRTXdF6IDsnGKQe77FRFP4H7M=/fit-in/246x300/filters:strip_icc()/pic5687013.jpg' where not exists (select 1 from games where name = '스페이스 크루: 9번째 행성을 찾아서');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '보드게임', '닉네임', 'nickname', '파티, 기억력', null, '3~6인', 15, 'https://boardlife.co.kr/game/13051', null, null where not exists (select 1 from games where name = '닉네임');
update games set name = '후엠아이 내가 누구게?', name_original = 'Who Am I', category = '파티', expansion = null, players = null, play_minutes = null, link = 'https://boardlife.co.kr/game/12101/collection', bgg_id = null, image_url = coalesce(image_url, null) where id = 24;
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '보드게임', '피냐타 로카', 'Piñata Loca', '블러핑, 추리, 카드', null, '2~6인', 30, 'https://boardgamegeek.com/boardgame/219489', 219489, 'https://cf.geekdo-images.com/6cO1AcI9jFGDmHaAoRjVkg__itemrep/img/r3KnG0ophudC3LIdXfpOaDZGHHA=/fit-in/246x300/filters:strip_icc()/pic3430374.jpg' where not exists (select 1 from games where name = '피냐타 로카');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '보드게임', '이게 왜? 오리너구리', 'Platypus', '파티, 추리(협력 단어)', null, '2~8인', 30, 'https://boardgamegeek.com/boardgame/322739', 322739, 'https://cf.geekdo-images.com/X6u5DUgUeOEMvZ0HXQmOJQ__itemrep/img/RmYhamd-2NtxALn0VUbMzPOYGHY=/fit-in/246x300/filters:strip_icc()/pic5897451.jpg' where not exists (select 1 from games where name = '이게 왜? 오리너구리');
update games set name = '우노', name_original = 'UNO', category = '카드, 가족', expansion = null, players = '2~10인', play_minutes = 30, link = 'https://boardgamegeek.com/boardgame/2223', bgg_id = 2223, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/-DHiHBBSnvaLu0Do8CIykQ__itemrep/img/m4GOPbjQ_C6lclrlQQqvLkVtyo8=/fit-in/246x300/filters:strip_icc()/pic8204165.jpg') where id = 33;
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '보드게임', '우리들의 여름방학', 'なつめも (Natsumemo, 2019)', '플립 앤 라이트, 파티', null, '3~6인', 45, 'https://boardgamegeek.com/boardgame/280811', 280811, 'https://cf.geekdo-images.com/0Ks4EWWGr9znEC03C78CsQ__itemrep/img/qUDxqR8l5XD9uunhbgMcoWCx884=/fit-in/246x300/filters:strip_icc()/pic4976425.jpg' where not exists (select 1 from games where name = '우리들의 여름방학');
update games set name = '스플렌더', name_original = 'Splendor', category = '엔진빌딩, 카드, 가족', expansion = null, players = '2~4인', play_minutes = 30, link = 'https://boardgamegeek.com/boardgame/148228', bgg_id = 148228, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/vNFe4JkhKAERzi4T0Ntwpw__itemrep/img/OoBoVLPl4ZYiNioNIKlV_0HLEYQ=/fit-in/246x300/filters:strip_icc()/pic8234167.png') where id = 7;
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '보드게임', '슈머 허멜', 'Schummel Hummel', '카드, 파티(속임수 허용)', null, '3~5인', 25, 'https://boardgamegeek.com/boardgame/235944', 235944, 'https://cf.geekdo-images.com/LMQMtwzxH6X0_jSCtEbCjQ__itemrep/img/SqEczTH6Qacp7RfXEyhSFrNanO8=/fit-in/246x300/filters:strip_icc()/pic3753025.png' where not exists (select 1 from games where name = '슈머 허멜');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '보드게임', '타란툴라 탱고', 'Tarantel Tango', '실시간, 순발력, 파티', null, '2~5인', 20, 'https://boardgamegeek.com/boardgame/55833', 55833, 'https://cf.geekdo-images.com/pH7LU9dJd6hC5hPCZEqSBg__itemrep/img/NjYYkrOVIKOLCH9ujNATPGw7mQs=/fit-in/246x300/filters:strip_icc()/pic588138.jpg' where not exists (select 1 from games where name = '타란툴라 탱고');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '보드게임', '도미넌트 스피시즈', 'Dominant Species', '전략, 영향력/지역 장악', null, '2~6인', 240, 'https://boardgamegeek.com/boardgame/62219', 62219, 'https://cf.geekdo-images.com/oeygRZntjNUJWvc8SxDfww__itemrep/img/x4ww31_ekLbL-wQBhxyFZ3qEYtw=/fit-in/246x300/filters:strip_icc()/pic784193.jpg' where not exists (select 1 from games where name = '도미넌트 스피시즈');
update games set name = '네이션스: 더 다이스 게임', name_original = 'Nations: The Dice Game', category = '주사위, 문명', expansion = null, players = '1~4인', play_minutes = 40, link = 'https://boardgamegeek.com/boardgame/157809', bgg_id = 157809, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/cAUrzJCm1nNzJ_JyH6N85g__itemrep/img/-Yxrb8a3TQjhwjHko_fejE2dRGI=/fit-in/246x300/filters:strip_icc()/pic3743789.jpg') where id = 31;
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '보드게임', '펭귄 얼음깨기', 'Penguin Trap', '어린이, 손재주', null, '2~4인', 10, 'https://boardgamegeek.com/boardgame/225981', 225981, 'https://cf.geekdo-images.com/sRmZOQbfpODk1-Eu8qUwfQ__itemrep/img/8NP2TrgQYEmi8hX-N__Bartsb8U=/fit-in/246x300/filters:strip_icc()/pic3534841.jpg' where not exists (select 1 from games where name = '펭귄 얼음깨기');
update games set name = '5분 미스터리', name_original = '5-Minute Mystery', category = '실시간 협력, 추리', expansion = null, players = '1~6인', play_minutes = 30, link = 'https://boardgamegeek.com/boardgame/294514', bgg_id = 294514, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/lVXcyP_YIcG4EtzjAQXIVg__itemrep/img/6KcS2f43tyeSIQ3dknQNFXWwiAk=/fit-in/246x300/filters:strip_icc()/pic9745239.png') where id = 30;
update games set name = '어나니머스', name_original = 'Anonymous', category = '추리, 마피아(팀 블러핑)', expansion = null, players = '2~5인', play_minutes = 35, link = 'https://boardlife.co.kr/game/10617', bgg_id = null, image_url = coalesce(image_url, null) where id = 13;
update games set name = '판타지 왕국', name_original = 'Fantasy Realms', category = '카드 콤보, 가족', expansion = null, players = '2~6인', play_minutes = 20, link = 'https://boardgamegeek.com/boardgame/223040', bgg_id = 223040, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/A7IOpPt-lHrMYsbRmxXWdQ__itemrep/img/jI1OdHfT1AbmN-AU7zl241CDcm4=/fit-in/246x300/filters:strip_icc()/pic6177962.jpg') where id = 28;
update games set name = '데드 오브 윈터: 크로스로드 게임', name_original = 'Dead of Winter: A Crossroads Game', category = '준협력, 배신자, 좀비', expansion = null, players = '2~5인', play_minutes = 120, link = 'https://boardgamegeek.com/boardgame/150376', bgg_id = 150376, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/g4mV4BH-ZrhMUVgil-yV1A__itemrep/img/Tc76KEZmrLgCrsvhQAW36iv7x9E=/fit-in/246x300/filters:strip_icc()/pic3016500.jpg') where id = 29;
update games set name = '플레임크래프트', name_original = 'Flamecraft', category = '일꾼배치, 카드, 가족', expansion = null, players = '1~5인', play_minutes = 60, link = 'https://boardgamegeek.com/boardgame/336986', bgg_id = 336986, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/EvGtnsBDcfnKiqSiXHothQ__itemrep/img/jX6vD-lydthyBuFRXuuWOnkayh0=/fit-in/246x300/filters:strip_icc()/pic6605448.jpg') where id = 8;
update games set name = '카네기', name_original = 'Carnegie', category = '경제, 전략', expansion = null, players = '1~4인', play_minutes = 120, link = 'https://boardgamegeek.com/boardgame/310873', bgg_id = 310873, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/0qxz9DRRhsJrIW1TJ-kz0w__itemrep/img/4pTEwp2O7jkGZ0RoKG0kWKKOtPo=/fit-in/246x300/filters:strip_icc()/pic5710736.jpg') where id = 10;
update games set name = '트라야누스', name_original = 'Trajan', category = '만칼라 액션선택, 전략', expansion = null, players = '2~4인', play_minutes = 120, link = 'https://boardgamegeek.com/boardgame/102680', bgg_id = 102680, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/djdeCr__iNV5rMnGnxNiaQ__itemrep/img/MRLesoQwp4pzMnF4B-_FiyJzbK0=/fit-in/246x300/filters:strip_icc()/pic4336095.png') where id = 12;
update games set name = '피자의 달인', name_original = 'Pizzeria', category = '셋컬렉션, 필러', expansion = null, players = null, play_minutes = null, link = 'https://boardlife.co.kr/game/14666', bgg_id = null, image_url = coalesce(image_url, null) where id = 2;
update games set name = '웰컴투: 행복한 나의 집', name_original = 'Welcome To...', category = '플립 앤 라이트, 가족', expansion = null, players = '1~100인', play_minutes = 25, link = 'https://boardgamegeek.com/boardgame/233867', bgg_id = 233867, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/g4XmxyKhNVdhC3QPd1purQ__itemrep/img/QKJwfdV3Qrv9w2TX_ML5T3z5G9E=/fit-in/246x300/filters:strip_icc()/pic3761012.jpg') where id = 27;
update games set name = '해녀', name_original = '해녀: Sea Divers of Jeju', category = '카드, 환경, 가족', expansion = null, players = '2~5인', play_minutes = 40, link = 'https://boardgamegeek.com/boardgame/468868', bgg_id = 468868, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/siUEgwQgNvxyg2sDpc1PlA__itemrep/img/lzJkmB24Lhghkyu3IoL2XVN_HiA=/fit-in/246x300/filters:strip_icc()/pic9531187.jpg') where id = 25;
update games set name = '데드 바이 데이라이트 보드게임: 컬렉터스 에디션', name_original = 'Dead by Daylight: The Board Game – Collector''s Edition', category = '비대칭 대전, 호러', expansion = null, players = '3~5인', play_minutes = 60, link = 'https://boardgamegeek.com/boardgame/358246', bgg_id = 358246, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/fpnjJSQWpAh1WZW3zJ807A__itemrep/img/0FyP7gUgtFxQS8vq2p_VocShE84=/fit-in/246x300/filters:strip_icc()/pic6727475.jpg') where id = 22;
update games set name = '메나라', name_original = 'Menara', category = '협력, 손재주(쌓기)', expansion = null, players = '1~4인', play_minutes = 60, link = 'https://boardgamegeek.com/boardgame/244608', bgg_id = 244608, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/qRwLtZZDhIT1wPD8qjCEUA__itemrep/img/Tw9QUj-Zy37cL_VmPmjjLF05GQQ=/fit-in/246x300/filters:strip_icc()/pic3944407.jpg') where id = 23;
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '보드게임', '시계탑에 흐른 피', 'Blood on the Clocktower', '소셜 디덕션, 블러핑', null, '6~21인', 120, 'https://boardgamegeek.com/boardgame/240980', 240980, 'https://cf.geekdo-images.com/HINb2nkFn5IiZxAlzQIs4g__itemrep/img/ji9nruIqJkNi8omWgNRZKmrZjwA=/fit-in/246x300/filters:strip_icc()/pic7009391.jpg' where not exists (select 1 from games where name = '시계탑에 흐른 피');
update games set name = '아르낙의 잊혀진 유적', name_original = 'Lost Ruins of Arnak', category = '덱빌딩+일꾼배치, 탐험', expansion = '탐험대장, 사라진 탐험대, 모험의 궤', players = '1~4인', play_minutes = 120, link = 'https://boardgamegeek.com/boardgame/312484', bgg_id = 312484, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/6GqH14TJJhza86BX5HCLEQ__itemrep/img/ETni1QwddAVjM-xLhciF0UM0FxQ=/fit-in/246x300/filters:strip_icc()/pic5674958.jpg') where id = 26;
update games set name = '오딘을 위하여', name_original = 'A Feast for Odin', category = '일꾼배치, 타일 퍼즐', expansion = '노르웨이 사람들', players = '1~4인', play_minutes = 120, link = 'https://boardgamegeek.com/boardgame/177736', bgg_id = 177736, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/s9oGMCo1fcfV4Dk3EnqLZw__itemrep/img/IRX2-uakhv7gHZPJNmtDbWFpjLg=/fit-in/246x300/filters:strip_icc()/pic3146943.png') where id = 11;
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '보드게임', '위대한 로렌초', 'Lorenzo il Magnifico: Big Box', '일꾼배치, 전략', '풀확장', '2~5인', 120, 'https://boardgamegeek.com/boardgame/338476', 338476, 'https://cf.geekdo-images.com/mEP17E6-KPX7oXgigks-Ww__itemrep/img/IalafwdSO9KoA1OjPJigc8VqxgU=/fit-in/246x300/filters:strip_icc()/pic6167555.jpg' where not exists (select 1 from games where name = '위대한 로렌초');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '보드게임', '캔버스', 'Canvas', '카드 레이어링, 퍼즐, 가족', '리플렉션, 피니싱 터치', '1~5인', 30, 'https://boardgamegeek.com/boardgame/290236', 290236, 'https://cf.geekdo-images.com/kXJLvPqcDF7Id5KRejhnuQ__itemrep/img/CFlfRLohmuN0a-Oic_j21n7rhNM=/fit-in/246x300/filters:strip_icc()/pic7125372.jpg' where not exists (select 1 from games where name = '캔버스');
insert into games (kind, name, name_original, category, expansion, players, play_minutes, link, bgg_id, image_url) select '보드게임', '콩코르디아', 'Concordia', '덱빌딩, 경제', '소금', '2~5인', 100, 'https://boardgamegeek.com/boardgame/124361', 124361, 'https://cf.geekdo-images.com/CzwSm8i7tkLz6cBnrILZBg__itemrep/img/kYm-P2lvyVstKDjvEDciaV3XObg=/fit-in/246x300/filters:strip_icc()/pic3453267.jpg' where not exists (select 1 from games where name = '콩코르디아');
update games set name = '테오티우아칸: 신들의 도시', name_original = 'Teotihuacan: City of Gods', category = '주사위 일꾼, 전략', expansion = '전고전기 후기, 시틀레에 드리운 암운', players = '1~4인', play_minutes = 120, link = 'https://boardgamegeek.com/boardgame/229853', bgg_id = 229853, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/wW5xjgBJcFyLaEWZwrYuKA__itemrep/img/3QLqMVpqfJ9IeVBnJVCE06T3Zhk=/fit-in/246x300/filters:strip_icc()/pic4583626.jpg') where id = 32;
update games set name = '하트 오브 크라운', name_original = 'Heart of Crown', category = '덱빌딩', expansion = '극동변방령, 북쪽 끝의 마녀', players = '2~4인', play_minutes = 60, link = 'https://boardgamegeek.com/boardgame/131904', bgg_id = 131904, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/HkLpn-ctptcufzbg_I_MkA__itemrep/img/ZYUDTmn3yQWsrvqXcT65bIkJCps=/fit-in/246x300/filters:strip_icc()/pic7111597.jpg') where id = 6;
update games set name = '촐킨: 마야의 달력', name_original = 'Tzolk''in: The Mayan Calendar', category = '일꾼배치(톱니바퀴), 전략', expansion = '부족과 예언', players = '2~5인', play_minutes = 90, link = 'https://boardgamegeek.com/boardgame/126163', bgg_id = 126163, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/kXf7mDyDYuHg6oe8yTUIEA__itemrep/img/8M-vck69HAdoJdStBZ8q91-7hRs=/fit-in/246x300/filters:strip_icc()/pic4604439.jpg') where id = 9;
update games set name = '태양 너머로', name_original = 'Beyond the Sun', category = '테크트리, 문명/우주', expansion = '새 여명의 지도자들', players = '1~4인', play_minutes = 120, link = 'https://boardgamegeek.com/boardgame/317985', bgg_id = 317985, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/BfEHqHQAvZLbRX7y7e9TWg__itemrep/img/kSw_dxGnXuq6trYpz7ob53-u2uU=/fit-in/246x300/filters:strip_icc()/pic5617866.jpg') where id = 14;
update games set name = '광기의 저택 (2판)', name_original = 'Mansions of Madness: Second Edition', category = '앱 연동 협력, 호러, 미니어처', expansion = '끔찍한 여정, 뱀이 서린 길', players = '1~5인', play_minutes = 180, link = 'https://boardgamegeek.com/boardgame/205059', bgg_id = 205059, image_url = coalesce(image_url, 'https://cf.geekdo-images.com/LIooA9bTdjnE9qmhjL-UFw__itemrep/img/G_-z236LOfeZMfomDg5oPNJvyrg=/fit-in/246x300/filters:strip_icc()/pic3118622.jpg') where id = 4;

select kind, count(*) from games group by kind;
